### ISSUE TITLE
Mule 4.4.0-20221111 - Configuration must first start for OpenTelemetry connection.

### ISSUE THREAD

**Issue by cmilazzo** [avioconsulting/mule-opentelemetry-module#105]
Seeing that error when trying to configure the extension to connect to Dynatrace.   Is there an example config I can use for dyntrace?  There is one for splunk and Elastic but not one for Dynatrace. 

	<opentelemetry:config name="OpenT" doc:name="OpenTelemetry Config" doc:id="1ba5ec3f-66f2-47ff-aa4b-f23012a9b2dc" serviceName="TEST" >
		<opentelemetry:connection />
		<opentelemetry:exporter >
			<opentelemetry:otlp-exporter collectorEndpoint="https://hostname/e/xxxxxxxxxxxx/api/v2/otlp/v1" protocol="HTTP_PROTOBUF" requestCompression="GZIP" />
		</opentelemetry:exporter>
	</opentelemetry:config>

INFO  2023-09-14 16:48:21,541 [[MuleRuntime].uber.04: [instrumentation].uber@org.mule.runtime.core.internal.connection.DefaultConnectivityTesterFactory$1.testConnectivity:81 @61ad491e] [processor: ; event: ] org.mule.runtime.core.internal.connection.DefaultConnectivityTesterFactory: Connectivity test failed for config 'OpenTelemetry_Config'. Application deployment will continue. Error was: Configuration must first start for OpenTelemetry connection.
org.mule.runtime.api.connection.ConnectionException: Configuration must first start for OpenTelemetry connection.
	at com.avioconsulting.mule.opentelemetry.internal.connection.OpenTelemetryConnectionProvider.lambda$connect$0(OpenTelemetryConnectionProvider.java:26) ~[mule-opentelemetry-module-1.2.1-mule-plugin.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_161]
	at com.avioconsulting.mule.opentelemetry.internal.connection.OpenTelemetryConnectionProvider.connect(OpenTelemetryConnectionProvider.java:25) ~[mule-opentelemetry-module-1.2.1-mule-plugin.jar:?]
	at com.avioconsulting.mule.opentelemetry.internal.connection.OpenTelemetryConnectionProvider.connect(OpenTelemetryConnectionProvider.java:12) ~[mule-opentelemetry-module-1.2.1-mule-plugin.jar:?]
	at org.mule.runtime.module.extension.internal.runtime.config.ClassLoaderConnectionProviderWrapper.connect(ClassLoaderConnectionProviderWrapper.java:60) ~[mule-module-extensions-support-4.4.0-20221111.jar:4.4.0-20221111]
	at org.mule.runtime.core.internal.connection.ConnectionUtils.connect(ConnectionUtils.java:52) ~[mule-core-4.4.0-20221111.jar:4.4.0-20221111]
	at org.mule.runtime.core.internal.connection.AbstractConnectionProviderWrapper.connect(AbstractConnectionProviderWrapper.java:63) ~[mule-core-4.4.0-20221111.jar:4.4.0-20221111]
	at org.mule.runtime.core.internal.connection.ErrorTypeHandlerConnectionProviderWrapper.connect(ErrorTypeHandlerConnectionProviderWrapper.java:64) ~[mule-core-4.4.0-20221111.jar:4.4.0-20221111]
	at org.mule.runtime.core.internal.connection.ConfigNameResolverConnectionProviderWrapper.connect(ConfigNameResolverConnectionProviderWrapper.java:50) ~[mule-core-4.4.0-20221111.jar:4.4.0-20221111]
	at org.mule.runtime.core.internal.connection.ConnectionUtils.connect(ConnectionUtils.java:52) ~[mule-core-4.4.0-20221111.jar:4.4.0-20221111]
	at org.mule.runtime.core.internal.connection.AbstractConnectionProviderWrapper.connect(AbstractConnectionProviderWrapper.java:63) ~[mule-core-4.4.0-20221111.jar:4.4.0-20221111]
	at org.mule.runtime.core.internal.connection.DefaultConnectionProviderWrapper.connect(DefaultConnectionProviderWrapper.java:52) ~[mule-core-4.4.0-20221111.jar:4.4.0-20221111]
	at org.mule.runtime.core.internal.connection.CachedConnectionManagementStrategy.createConnection(CachedConnectionManagementStrategy.java:95) ~[mule-core-4.4.0-20221111.jar:4.4.0-20221111]
	at org.mule.runtime.core.api.util.func.CheckedSupplier.get(CheckedSupplier.java:25) ~[mule-core-4.4.0-20221111.jar:4.4.0-20221111]
	at org.mule.runtime.api.util.LazyValue.get(LazyValue.java:75) ~[mule-api-1.4.0-20221111.jar:?]
	at org.mule.runtime.core.internal.connection.CachedConnectionManagementStrategy.getConnectionHandler(CachedConnectionManagementStrategy.java:63) ~[mule-core-4.4.0-20221111.jar:4.4.0-20221111]
	at org.mule.runtime.core.internal.connection.DefaultConnectionManager.getConnection(DefaultConnectionManager.java:247) ~[mule-core-4.4.0-20221111.jar:4.4.0-20221111]
	at org.mule.runtime.core.internal.connection.DefaultConnectionManager.lambda$testConnectivity$1(DefaultConnectionManager.java:166) ~[mule-core-4.4.0-20221111.jar:4.4.0-20221111]
	at org.mule.runtime.core.internal.connection.DefaultConnectionManager.doTestConnectivity(DefaultConnectionManager.java:182) ~[mule-core-4.4.0-20221111.jar:4.4.0-20221111]
	at org.mule.runtime.core.internal.connection.DefaultConnectionManager.testConnectivity(DefaultConnectionManager.java:158) ~[mule-core-4.4.0-20221111.jar:4.4.0-20221111]
	at org.mule.runtime.core.internal.connection.DelegateConnectionManagerAdapter$EagerConnectionManagerAdapter.testConnectivity(DelegateConnectionManagerAdapter.java:176) ~[mule-core-4.4.0-20221111.jar:4.4.0-20221111]
	at org.mule.runtime.core.internal.connection.DelegateConnectionManagerAdapter.testConnectivity(DelegateConnectionManagerAdapter.java:98) ~[mule-core-4.4.0-20221111.jar:4.4.0-20221111]
	at org.mule.runtime.core.internal.connection.DefaultConnectivityTesterFactory$1$1.doWork(DefaultConnectivityTesterFactory.java:95) [mule-core-4.4.0-20221111.jar:4.4.0-20221111]
	at org.mule.runtime.core.api.retry.policy.AbstractPolicyTemplate.execute(AbstractPolicyTemplate.java:62) [mule-core-4.4.0-20221111.jar:4.4.0-20221111]
	at org.mule.runtime.core.internal.retry.async.RetryWorker.run(RetryWorker.java:56) [mule-core-4.4.0-20221111.jar:4.4.0-20221111]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
	at org.mule.service.scheduler.internal.AbstractRunnableFutureDecorator.doRun(AbstractRunnableFutureDecorator.java:151) [mule-service-scheduler-1.4.3/:?]
	at org.mule.service.scheduler.internal.RunnableFutureDecorator.run(RunnableFutureDecorator.java:54) [mule-service-scheduler-1.4.3/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]

**Comment by manikmagar** [comment]
Hi @cmilazzo, when do you see that error - during connection testing from the studio Or at the application startup time? Have you tried running the application and seeing if that only appears during startup or the first time but then traces make it to the Dynatrace?

**Comment by cmilazzo** [comment]
I see it both during test connection and during startup ( both in studio and runtime ) 

Once this is done I am looking at the trace this is generating with dynatrace and dont see any differences. 

Should the normal trace be enriched or should it be a seperate trace?

**Comment by manikmagar** [comment]
@cmilazzo I would ignore both in studio and at the startup since OTEL SDK initialization is lazy and Mule SDK's initial connections tests would result in this error. But once the application is running, you should be able to see traces generated from the mule app in Dynatrace.

I am not sure what you mean by "dont see any differences." and normal/enriched traces. Do you see any trace from your Mule app at all or Nothing?  Could you add any debug logs from the app?
