### ISSUE TITLE
Opentellemetry | Mule Notification Listener fails to End flow when I use Flow reference to a shared Library flow.

### ISSUE THREAD

**Issue by AwaisOmer** [avioconsulting/mule-opentelemetry-module#79]
Here Is my Error Details:

```
ERROR 2022-10-17 18:05:50,046 [[MuleRuntime].uber.06: [demo-error-handling-test-sapi].torei-exception-api.BLOCKING @22a279b6] [processor: ; event: 6c281390-4e1c-11ed-9d6e-0af81690783c] com.avioconsulting.mule.opentelemetry.internal.processor.MuleNotificationProcessor: Error in handling api-main flow end event
java.lang.NumberFormatException: For input string: [org.mule.runtime.core.internal.streaming.bytes.ManagedCursorStreamProvider@214c4497](mailto:org.mule.runtime.core.internal.streaming.bytes.ManagedCursorStreamProvider@214c4497)
      at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_332]
      at java.lang.Integer.parseInt(Integer.java:580) ~[?:1.8.0_332]
      at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_332]
      at com.avioconsulting.mule.opentelemetry.internal.processor.HttpProcessorComponent.getSourceEndTraceComponent(HttpProcessorComponent.java:196) ~[?:?]
      at com.avioconsulting.mule.opentelemetry.internal.processor.FlowProcessorComponent.lambda$getSourceEndTraceComponent$2(FlowProcessorComponent.java:113) ~[?:?]
      at java.util.Optional.flatMap(Optional.java:241) ~[?:1.8.0_332]
      at com.avioconsulting.mule.opentelemetry.internal.processor.FlowProcessorComponent.getSourceEndTraceComponent(FlowProcessorComponent.java:113) ~[?:?]
      at com.avioconsulting.mule.opentelemetry.internal.processor.MuleNotificationProcessor.handleFlowEndEvent(MuleNotificationProcessor.java:157) ~[?:?]
      at com.avioconsulting.mule.opentelemetry.internal.listeners.MulePipelineMessageNotificationListener.onNotification(MulePipelineMessageNotificationListener.java:40) ~[?:?]
      at com.avioconsulting.mule.opentelemetry.internal.listeners.MulePipelineMessageNotificationListener.onNotification(MulePipelineMessageNotificationListener.java:12) ~[?:?]
      at org.mule.runtime.core.api.context.notification.ServerNotificationManager.lambda$fireNotification$0(ServerNotificationManager.java:196) ~[mule-core-4.3.0-20220824.jar:4.3.0-20220824]
      at org.mule.runtime.core.internal.context.notification.Sender.dispatch(Sender.java:28) ~[mule-core-4.3.0-20220824.jar:4.3.0-20220824]
      at org.mule.runtime.core.internal.context.notification.Policy.dispatchToSenders(Policy.java:145) ~[mule-core-4.3.0-20220824.jar:4.3.0-20220824]
      at org.mule.runtime.core.internal.context.notification.Policy.doDispatch(Policy.java:120) ~[mule-core-4.3.0-20220824.jar:4.3.0-20220824]
      at org.mule.runtime.core.internal.context.notification.Policy.dispatch(Policy.java:106) ~[mule-core-4.3.0-20220824.jar:4.3.0-20220824]
      at org.mule.runtime.core.api.context.notification.ServerNotificationManager.notifyListeners(ServerNotificationManager.java:214) ~[mule-core-4.3.0-20220824.jar:4.3.0-20220824]
      at org.mule.runtime.core.api.context.notification.ServerNotificationManager.fireNotification(ServerNotificationManager.java:196) ~[mule-core-4.3.0-20220824.jar:4.3.0-20220824]
      at org.mule.runtime.core.internal.context.notification.DefaultNotificationDispatcher.dispatch(DefaultNotificationDispatcher.java:40) ~[mule-core-4.3.0-20220824.jar:4.3.0-20220824]
      at org.mule.runtime.core.internal.construct.AbstractPipeline.fireCompleteNotification(AbstractPipeline.java:447) ~[mule-core-4.3.0-20220824.jar:4.3.0-20220824]
      at org.mule.runtime.core.internal.construct.AbstractPipeline.lambda$null$22(AbstractPipeline.java:431) ~[mule-core-4.3.0-20220824.jar:4.3.0-20220824]
      at org.mule.runtime.core.internal.event.AbstractEventContext.signalConsumerSilently(AbstractEventContext.java:283) ~[mule-core-4.3.0-20220824.jar:4.3.0-20220824]
      at org.mule.runtime.core.internal.event.AbstractEventContext.tryComplete(AbstractEventContext.java:234) ~[mule-core-4.3.0-20220824.jar:4.3.0-20220824]
      at org.mule.runtime.core.internal.event.AbstractEventContext.lambda$tryComplete$6(AbstractEventContext.java:239) ~[mule-core-4.3.0-20220824.jar:4.3.0-20220824]
      at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_332]
      at org.mule.runtime.core.internal.event.AbstractEventContext.tryComplete(AbstractEventContext.java:237) ~[mule-core-4.3.0-20220824.jar:4.3.0-20220824]
      at org.mule.runtime.core.internal.event.AbstractEventContext.lambda$tryComplete$6(AbstractEventContext.java:239) ~[mule-core-4.3.0-20220824.jar:4.3.0-20220824]
      at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_332]
      at org.mule.runtime.core.internal.event.AbstractEventContext.tryComplete(AbstractEventContext.java:237) ~[mule-core-4.3.0-20220824.jar:4.3.0-20220824]
      at org.mule.runtime.core.internal.event.AbstractEventContext.responseDone(AbstractEventContext.java:213) ~[mule-core-4.3.0-20220824.jar:4.3.0-20220824]
      at org.mule.runtime.core.internal.event.AbstractEventContext.success(AbstractEventContext.java:160) ~[mule-core-4.3.0-20220824.jar:4.3.0-20220824]
      at org.mule.runtime.core.internal.construct.AbstractPipeline.lambda$afterProcessors$24(AbstractPipeline.java:456) ~[mule-core-4.3.0-20220824.jar:4.3.0-20220824]
      at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onNext(FluxPeekFuseable.java:832) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onNext(MonoFlatMapMany.java:242) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onNext(MonoFlatMapMany.java:242) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onNext(MonoFlatMapMany.java:242) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:204) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:204) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onNext(FluxContextStart.java:103) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:793) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.publisher.FluxCreate$BufferAsyncSink.next(FluxCreate.java:718) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.publisher.FluxCreate$SerializedSink.next(FluxCreate.java:153) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at org.mule.runtime.core.internal.rx.FluxSinkRecorder$DirectDelegate.next(FluxSinkRecorder.java:196) ~[mule-core-4.3.0-20220824.jar:4.3.0-20220824]
      at org.mule.runtime.core.internal.rx.FluxSinkRecorder.next(FluxSinkRecorder.java:68) ~[mule-core-4.3.0-20220824.jar:4.3.0-20220824]
      at org.mule.runtime.core.privileged.processor.chain.AbstractMessageProcessorChain.lambda$null$8(AbstractMessageProcessorChain.java:207) ~[mule-core-4.3.0-20220824.jar:4.3.0-20220824]
      at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onNext(FluxMapFuseable.java:273) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.onNext(FluxPeekFuseable.java:496) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onNext(FluxContextStart.java:103) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onNext(FluxContextStart.java:103) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onNext(FluxContextStart.java:103) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:213) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onNext(MonoFlatMapMany.java:242) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onNext(FluxContextStart.java:103) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at org.mule.runtime.core.privileged.processor.chain.AbstractMessageProcessorChain$2.onNext(AbstractMessageProcessorChain.java:448) ~[mule-core-4.3.0-20220824.jar:4.3.0-20220824]
      at org.mule.runtime.core.privileged.processor.chain.AbstractMessageProcessorChain$2.onNext(AbstractMessageProcessorChain.java:443) ~[mule-core-4.3.0-20220824.jar:4.3.0-20220824]
      at reactor.core.publisher.FluxFlatMap$FlatMapMain.tryEmit(FluxFlatMap.java:537) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.publisher.FluxFlatMap$FlatMapInner.onNext(FluxFlatMap.java:999) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onNext(MonoFlatMapMany.java:242) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onNext(MonoFlatMapMany.java:242) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:204) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:204) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onNext(FluxContextStart.java:103) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:793) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.publisher.FluxCreate$BufferAsyncSink.next(FluxCreate.java:718) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.publisher.FluxCreate$SerializedSink.next(FluxCreate.java:153) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at org.mule.runtime.core.internal.rx.FluxSinkRecorder$DirectDelegate.next(FluxSinkRecorder.java:196) ~[mule-core-4.3.0-20220824.jar:4.3.0-20220824]
      at org.mule.runtime.core.internal.rx.FluxSinkRecorder.next(FluxSinkRecorder.java:68) ~[mule-core-4.3.0-20220824.jar:4.3.0-20220824]
      at org.mule.runtime.core.privileged.processor.chain.AbstractMessageProcessorChain.lambda$null$8(AbstractMessageProcessorChain.java:207) ~[mule-core-4.3.0-20220824.jar:4.3.0-20220824]
      at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onNext(FluxMapFuseable.java:273) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.onNext(FluxPeekFuseable.java:496) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onNext(FluxContextStart.java:103) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onNext(FluxContextStart.java:103) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onNext(FluxContextStart.java:103) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:213) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onNext(MonoFlatMapMany.java:242) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onNext(FluxContextStart.java:103) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at org.mule.runtime.core.privileged.processor.chain.AbstractMessageProcessorChain$2.onNext(AbstractMessageProcessorChain.java:448) ~[mule-core-4.3.0-20220824.jar:4.3.0-20220824]
      at org.mule.runtime.core.privileged.processor.chain.AbstractMessageProcessorChain$2.onNext(AbstractMessageProcessorChain.java:443) ~[mule-core-4.3.0-20220824.jar:4.3.0-20220824]
      at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onNext(MonoFlatMapMany.java:242) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:192) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:192) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:192) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onNext(MonoFlatMapMany.java:242) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:204) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:204) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onNext(FluxContextStart.java:103) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:793) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.publisher.FluxCreate$BufferAsyncSink.next(FluxCreate.java:718) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.publisher.FluxCreate$SerializedSink.next(FluxCreate.java:153) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at org.mule.runtime.core.internal.rx.FluxSinkRecorder$DirectDelegate.next(FluxSinkRecorder.java:196) ~[mule-core-4.3.0-20220824.jar:4.3.0-20220824]
      at org.mule.runtime.core.internal.rx.FluxSinkRecorder.next(FluxSinkRecorder.java:68) ~[mule-core-4.3.0-20220824.jar:4.3.0-20220824]
      at org.mule.runtime.module.extension.internal.runtime.operation.ComponentMessageProcessor$1.complete(ComponentMessageProcessor.java:383) ~[mule-module-extensions-support-4.3.0-20220824.jar:4.3.0-20220824]
      at org.mule.runtime.module.extension.internal.runtime.operation.ComponentMessageProcessor.lambda$null$18(ComponentMessageProcessor.java:696) ~[mule-module-extensions-support-4.3.0-20220824.jar:4.3.0-20220824]
      at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onNext(FluxPeekFuseable.java:832) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onNext(MonoFlatMapMany.java:242) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onNext(FluxContextStart.java:103) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onNext(MonoFlatMapMany.java:242) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onNext(MonoFlatMapMany.java:242) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:204) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:204) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onNext(FluxContextStart.java:103) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:793) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.publisher.FluxCreate$BufferAsyncSink.next(FluxCreate.java:718) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.publisher.FluxCreate$SerializedSink.next(FluxCreate.java:153) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at org.mule.runtime.core.internal.rx.FluxSinkRecorder$DirectDelegate.next(FluxSinkRecorder.java:196) ~[mule-core-4.3.0-20220824.jar:4.3.0-20220824]
      at org.mule.runtime.core.internal.rx.FluxSinkRecorder.next(FluxSinkRecorder.java:68) ~[mule-core-4.3.0-20220824.jar:4.3.0-20220824]
      at org.mule.runtime.module.extension.internal.runtime.operation.ComponentMessageProcessor$4$1.complete(ComponentMessageProcessor.java:665) ~[mule-module-extensions-support-4.3.0-20220824.jar:4.3.0-20220824]
      at org.mule.runtime.module.extension.internal.runtime.operation.ComponentMessageProcessor$3.complete(ComponentMessageProcessor.java:533) ~[mule-module-extensions-support-4.3.0-20220824.jar:4.3.0-20220824]
      at org.mule.runtime.module.extension.internal.runtime.operation.DefaultExecutionMediator$1.complete(DefaultExecutionMediator.java:160) ~[mule-module-extensions-support-4.3.0-20220824.jar:4.3.0-20220824]
      at org.mule.runtime.module.extension.internal.runtime.operation.DeferredExecutorCallback.callDelegateMethod(DeferredExecutorCallback.java:108) ~[mule-module-extensions-support-4.3.0-20220824.jar:4.3.0-20220824]
      at org.mule.runtime.module.extension.internal.runtime.operation.DeferredExecutorCallback.close(DeferredExecutorCallback.java:97) ~[mule-module-extensions-support-4.3.0-20220824.jar:4.3.0-20220824]
      at org.mule.runtime.module.extension.internal.runtime.operation.DefaultExecutionMediator.execute(DefaultExecutionMediator.java:128) ~[mule-module-extensions-support-4.3.0-20220824.jar:4.3.0-20220824]
      at org.mule.runtime.module.extension.internal.runtime.operation.ComponentMessageProcessor.executeOperation(ComponentMessageProcessor.java:570) ~[mule-module-extensions-support-4.3.0-20220824.jar:4.3.0-20220824]
      at org.mule.runtime.module.extension.internal.runtime.operation.ComponentMessageProcessor.prepareAndExecuteOperation(ComponentMessageProcessor.java:795) ~[mule-module-extensions-support-4.3.0-20220824.jar:4.3.0-20220824]
      at org.mule.runtime.module.extension.internal.runtime.operation.ComponentMessageProcessor.access$100(ComponentMessageProcessor.java:195) ~[mule-module-extensions-support-4.3.0-20220824.jar:4.3.0-20220824]
      at org.mule.runtime.module.extension.internal.runtime.operation.ComponentMessageProcessor$4.lambda$innerEventDispatcher$6(ComponentMessageProcessor.java:655) ~[mule-module-extensions-support-4.3.0-20220824.jar:4.3.0-20220824]
      at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.tryOnNext(FluxPeekFuseable.java:510) [reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.tryOnNext(FluxPeekFuseable.java:523) [reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.publisher.FluxPublishOn$PublishOnConditionalSubscriber.runAsync(FluxPublishOn.java:998) [reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.publisher.FluxPublishOn$PublishOnConditionalSubscriber.run(FluxPublishOn.java:1073) [reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) [reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) [reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
      at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_332]
      at org.mule.service.scheduler.internal.AbstractRunnableFutureDecorator.doRun(AbstractRunnableFutureDecorator.java:152) [mule-service-scheduler-1.3.4/:?]
      at org.mule.service.scheduler.internal.RunnableFutureDecorator.run(RunnableFutureDecorator.java:54) [mule-service-scheduler-1.3.4/:?]
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_332]
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_332]
      at java.lang.Thread.run(Thread.java:750) [?:1.8.0_332]
INFO  2022-10-17 18:05:50,057 [[MuleRuntime].uber.06: [demo-error-handling-test-sapi].torei-exception-api.BLOCKING @22a279b6] [processor: ; event: 6c281390-4e1c-11ed-9d6e-0af81690783c] org.mule.runtime.core.internal.context.notification.Policy: NotificationListener [com.avioconsulting.mule.opentelemetry.internal.listeners.MulePipelineMessageNotificationListener@588653d0](mailto:com.avioconsulting.mule.opentelemetry.internal.listeners.MulePipelineMessageNotificationListener@588653d0) was unable to fire notification PipelineMessageNotification{action=pipeline process complete, resourceId=api-main, serverId=WSAMZN-L7P5SV96..demo-error-handling-test-sapi, timestamp=1666011950046} due to an exception: java.lang.NumberFormatException: For input string: [org.mule.runtime.core.internal.streaming.bytes.ManagedCursorStreamProvider@214c4497](mailto:org.mule.runtime.core.internal.streaming.bytes.ManagedCursorStreamProvider@214c4497).

---------------------------------------------------------------------------------------
![MicrosoftTeams-image](https://user-images.githubusercontent.com/27624901/196186872-a1ac78e2-b7b7-4a0a-b8b2-38953c565993.png)

```

**Comment by manikmagar** [comment]
@AwaisOmer Can you check the value of `httpStatus` variable if your flow or referenced subflow `torei-exception-api` setting it to a valid HTTP Status code?

**Comment by AwaisOmer** [comment]
> @AwaisOmer Can you check the value of `httpStatus` variable if your flow or referenced subflow `torei-exception-api` setting it to a valid HTTP Status code?

Please see this, it is valid, I am setting httpStatus inside the shared library

![image](https://user-images.githubusercontent.com/27624901/196205287-27cdec7b-b679-431a-895f-bea6c0ce9494.png)

**Comment by manikmagar** [comment]
@AwaisOmer Seeing the mediaType as `application/json` and the error message, I think the issue is the media type of that variable. Runtime is using streams for json. Can you try removing that mediaType from the variable or just set it as a java `<set-variable variableName="httpStatus" value="#['200']"/>`?

java.lang.NumberFormatException: **For input string: [org.mule.runtime.core.internal.streaming.bytes.ManagedCursorStreamProvider@214c4497]**(mailto:org.mule.runtime.core.internal.streaming.bytes.ManagedCursorStreamProvider@214c4497)
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_332]

**Comment by AwaisOmer** [comment]
Yes Thanks Manik, that was indeed the issue. It is resolved now
